# Workflows

Sometimes, having to call multiple request and retrieve information to do consecutive requests can be tedious. Workflows allow you to chain multiple requests together, by using predefined steps.

## Creating a Workflow

In [1]:
from silkroute import Workflow

wf = Workflow()

To run a workflow object we need to first define the parameters of the workflow. The main ones are:

- modality: Depending on the type of dataset we want to retrieve, we can select between 'protein', 'compound' or 'interaction'. protein will retrieve protein sequences from UniProt, compound will retrieve small molecule structures from ChEMBL, and interaction will retrieve either protein-protein or protein-ligand interactions.
    
- mode: The mode defines the order of operations. There are three modes available:

    - query_first: In this mode, we first perform a query to retrieve identifiers, and then use those identifiers to retrieve the data.
        
    - import_first: In this mode, we first import a list of identifiers, and then use those identifiers to perform a query.
        
    - query_composition: In this mode, we perform multiple queries with labels, and then combine the results.
    
- query: For 'query_first' and 'query_composition' modes, we need to provide a query string to search for identifiers.
    
- enrich: Whether to perform enrichment of the retrieved data with additional information from other databases.
    
- search_type: If using 'compound' modality, we can define the type of search to perform. Options are 'activity' (to search for compounds with specific bioactivity) or 'target' (to search for compounds targeting specific proteins).
   
- interaction_type: If using 'interaction' modality, we can define the type of interaction to retrieve. Options are 'protein-protein' or 'protein-ligand'.
   
- export_format: The format in which to export the retrieved data. Options include 'csv', 'json', 'xml', 'parquet'.

## Search examples

### Compounds with specific bioactivity ic50 between 20 and 30 nM that have an associated alphafold structure

In [2]:
data, meta = wf.run(
    mode="query_first",
    modality="compound",
    search_type="activity",
    query="ic50:20-30 AND databases:alphafold",
    export_format="csv",
    enrich=True,
)

2026-02-05 19:18:11 | INFO     | silkroute.core.workflow.main | Pipeline: fetching ChEMBL for query=ic50>20 AND ic50<30 search_type=activity
2026-02-05 19:18:12 | WARNING  | silkroute.core.workflow.main | Pipeline: large number of ChEMBL IDs (282); UniProt query may be too long
2026-02-05 19:18:12 | INFO     | silkroute.core.workflow.main | Searches will be divided into chunks of 100 IDs
2026-02-05 19:18:12 | INFO     | silkroute.core.workflow.main | Pipeline: fetching UniProt for query=(database:alphafolddb) AND (xref:chembl-CHEMBL2189139 OR xref:chembl-CHEMBL203 OR xref:chembl-CHEMBL325 OR xref:chembl-CHEMBL3524 OR xref:chembl-CHEMBL3192 OR xref:chembl-CHEMBL1829 OR xref:chembl-CHEMBL4145 OR xref:chembl-CHEMBL1937 OR xref:chembl-CHEMBL1865 OR xref:chembl-CHEMBL3145 OR xref:chembl-CHEMBL612545 OR xref:chembl-CHEMBL613740 OR xref:chembl-CHEMBL2997 OR xref:chembl-CHEMBL4078 OR xref:chembl-CHEMBL4354 OR xref:chembl-CHEMBL375 OR xref:chembl-CHEMBL5936 OR xref:chembl-CHEMBL2039 OR xref:chembl-CHEMBL364 OR xref:chembl-CHEMBL340 OR xref:chembl-CHEMBL612558 OR xref:chembl-CHEMBL2815 OR xref:chembl-CHEMBL4888439 OR xref:chembl-CHEMBL2367379 OR xref:chembl-CHEMBL613870 OR xref:chembl-CHEMBL612557 OR xref:chembl-CHEMBL1907600 OR xref:chembl-CHEMBL3229 OR xref:chembl-CHEMBL5291954 OR xref:chembl-CHEMBL6136 OR xref:chembl-CHEMBL3832943 OR xref:chembl-CHEMBL5048 OR xref:chembl-CHEMBL2047 OR xref:chembl-CHEMBL4296244 OR xref:chembl-CHEMBL4296245 OR xref:chembl-CHEMBL335 OR xref:chembl-CHEMBL3879801 OR xref:chembl-CHEMBL3217380 OR xref:chembl-CHEMBL612262 OR xref:chembl-CHEMBL3649 OR xref:chembl-CHEMBL220 OR xref:chembl-CHEMBL3952 OR xref:chembl-CHEMBL3222 OR xref:chembl-CHEMBL2111396 OR xref:chembl-CHEMBL2111441 OR xref:chembl-CHEMBL1907607 OR xref:chembl-CHEMBL2111361 OR xref:chembl-CHEMBL614822 OR xref:chembl-CHEMBL321 OR xref:chembl-CHEMBL4247 OR xref:chembl-CHEMBL2111380 OR xref:chembl-CHEMBL3975 OR xref:chembl-CHEMBL5763 OR xref:chembl-CHEMBL1907608 OR xref:chembl-CHEMBL3356 OR xref:chembl-CHEMBL387 OR xref:chembl-CHEMBL368 OR xref:chembl-CHEMBL3114 OR xref:chembl-CHEMBL3513 OR xref:chembl-CHEMBL275 OR xref:chembl-CHEMBL3046 OR xref:chembl-CHEMBL4174 OR xref:chembl-CHEMBL6066863 OR xref:chembl-CHEMBL3180 OR xref:chembl-CHEMBL5848 OR xref:chembl-CHEMBL4523375 OR xref:chembl-CHEMBL6135 OR xref:chembl-CHEMBL2093872 OR xref:chembl-CHEMBL2362975 OR xref:chembl-CHEMBL378 OR xref:chembl-CHEMBL614004 OR xref:chembl-CHEMBL612881 OR xref:chembl-CHEMBL301 OR xref:chembl-CHEMBL369 OR xref:chembl-CHEMBL1075051 OR xref:chembl-CHEMBL612570 OR xref:chembl-CHEMBL339 OR xref:chembl-CHEMBL399 OR xref:chembl-CHEMBL614560 OR xref:chembl-CHEMBL394 OR xref:chembl-CHEMBL2949 OR xref:chembl-CHEMBL3004 OR xref:chembl-CHEMBL1914 OR xref:chembl-CHEMBL2094268 OR xref:chembl-CHEMBL3779755 OR xref:chembl-CHEMBL3559643 OR xref:chembl-CHEMBL2189117 OR xref:chembl-CHEMBL1667685 OR xref:chembl-CHEMBL384 OR xref:chembl-CHEMBL4523582 OR xref:chembl-CHEMBL4616 OR xref:chembl-CHEMBL3318 OR xref:chembl-CHEMBL2633 OR xref:chembl-CHEMBL614247 OR xref:chembl-CHEMBL392 OR xref:chembl-CHEMBL1951 OR xref:chembl-CHEMBL289 OR xref:chembl-CHEMBL3622 OR xref:chembl-CHEMBL4303 OR xref:chembl-CHEMBL4296487) fields=
2026-02-05 19:18:15 | INFO     | silkroute.core.workflow.main | Pipeline: fetching UniProt for query=(database:alphafolddb) AND (xref:chembl-CHEMBL1974 OR xref:chembl-CHEMBL3778 OR xref:chembl-CHEMBL3357 OR xref:chembl-CHEMBL258 OR xref:chembl-CHEMBL1913 OR xref:chembl-CHEMBL2041 OR xref:chembl-CHEMBL2079845 OR xref:chembl-CHEMBL379 OR xref:chembl-CHEMBL4375 OR xref:chembl-CHEMBL4905 OR xref:chembl-CHEMBL4780 OR xref:chembl-CHEMBL6066154 OR xref:chembl-CHEMBL2096991 OR xref:chembl-CHEMBL3471 OR xref:chembl-CHEMBL3397 OR xref:chembl-CHEMBL3650 OR xref:chembl-CHEMBL2858 OR xref:chembl-CHEMBL3575 OR xref:chembl-CHEMBL2842 OR xref:chembl-CHEMBL2094139 OR xref:chembl-CHEMBL4302 OR xref:chembl-CHEMBL1795117 OR xref:chembl-CHEMBL612446 OR xref:chembl-CHEMBL3559 OR xref:chembl-CHEMBL5393 OR xref:chembl-CHEMBL2095233 OR xref:chembl-CHEMBL614923 OR xref:chembl-CHEMBL398 OR xref:chembl-CHEMBL361 OR xref:chembl-CHEMBL4329 OR xref:chembl-CHEMBL614524 OR xref:chembl-CHEMBL385 OR xref:chembl-CHEMBL5137 OR xref:chembl-CHEMBL386 OR xref:chembl-CHEMBL2095155 OR xref:chembl-CHEMBL352 OR xref:chembl-CHEMBL5971 OR xref:chembl-CHEMBL389 OR xref:chembl-CHEMBL2094131 OR xref:chembl-CHEMBL2095201 OR xref:chembl-CHEMBL2111358 OR xref:chembl-CHEMBL614343 OR xref:chembl-CHEMBL3988582 OR xref:chembl-CHEMBL2111321 OR xref:chembl-CHEMBL612546 OR xref:chembl-CHEMBL3864 OR xref:chembl-CHEMBL4729 OR xref:chembl-CHEMBL3721 OR xref:chembl-CHEMBL2096618 OR xref:chembl-CHEMBL1741208 OR xref:chembl-CHEMBL5524 OR xref:chembl-CHEMBL612851 OR xref:chembl-CHEMBL4685 OR xref:chembl-CHEMBL2094253 OR xref:chembl-CHEMBL2111465 OR xref:chembl-CHEMBL2094125 OR xref:chembl-CHEMBL5502 OR xref:chembl-CHEMBL2095218 OR xref:chembl-CHEMBL2111475 OR xref:chembl-CHEMBL2093866 OR xref:chembl-CHEMBL3019 OR xref:chembl-CHEMBL1995 OR xref:chembl-CHEMBL3341582 OR xref:chembl-CHEMBL3092 OR xref:chembl-CHEMBL2581 OR xref:chembl-CHEMBL215 OR xref:chembl-CHEMBL3242 OR xref:chembl-CHEMBL3833502 OR xref:chembl-CHEMBL205 OR xref:chembl-CHEMBL614805 OR xref:chembl-CHEMBL2140 OR xref:chembl-CHEMBL613107 OR xref:chembl-CHEMBL4484 OR xref:chembl-CHEMBL2111442 OR xref:chembl-CHEMBL2095156 OR xref:chembl-CHEMBL2095151 OR xref:chembl-CHEMBL2111405 OR xref:chembl-CHEMBL2096621 OR xref:chembl-CHEMBL376 OR xref:chembl-CHEMBL2095185 OR xref:chembl-CHEMBL298 OR xref:chembl-CHEMBL2095149 OR xref:chembl-CHEMBL2095175 OR xref:chembl-CHEMBL2094252 OR xref:chembl-CHEMBL2097161 OR xref:chembl-CHEMBL2095220 OR xref:chembl-CHEMBL2095219 OR xref:chembl-CHEMBL2111418 OR xref:chembl-CHEMBL2096988 OR xref:chembl-CHEMBL397 OR xref:chembl-CHEMBL4015 OR xref:chembl-CHEMBL6120 OR xref:chembl-CHEMBL3407316 OR xref:chembl-CHEMBL4523140 OR xref:chembl-CHEMBL3438 OR xref:chembl-CHEMBL614309 OR xref:chembl-CHEMBL4523972 OR xref:chembl-CHEMBL400 OR xref:chembl-CHEMBL4026 OR xref:chembl-CHEMBL3717) fields=
2026-02-05 19:18:18 | INFO     | silkroute.core.workflow.main | Pipeline: fetching UniProt for query=(database:alphafolddb) AND (xref:chembl-CHEMBL1907611 OR xref:chembl-CHEMBL2095205 OR xref:chembl-CHEMBL2622 OR xref:chembl-CHEMBL2111350 OR xref:chembl-CHEMBL2096974 OR xref:chembl-CHEMBL2935 OR xref:chembl-CHEMBL3658 OR xref:chembl-CHEMBL614548 OR xref:chembl-CHEMBL3602 OR xref:chembl-CHEMBL614129 OR xref:chembl-CHEMBL2095213 OR xref:chembl-CHEMBL338 OR xref:chembl-CHEMBL4106 OR xref:chembl-CHEMBL286 OR xref:chembl-CHEMBL372 OR xref:chembl-CHEMBL1871 OR xref:chembl-CHEMBL1824 OR xref:chembl-CHEMBL2590 OR xref:chembl-CHEMBL1836 OR xref:chembl-CHEMBL2008 OR xref:chembl-CHEMBL1978 OR xref:chembl-CHEMBL614177 OR xref:chembl-CHEMBL2095152 OR xref:chembl-CHEMBL4296519 OR xref:chembl-CHEMBL4296 OR xref:chembl-CHEMBL390 OR xref:chembl-CHEMBL2003 OR xref:chembl-CHEMBL3706566 OR xref:chembl-CHEMBL3038469 OR xref:chembl-CHEMBL614909 OR xref:chembl-CHEMBL1862 OR xref:chembl-CHEMBL2097172 OR xref:chembl-CHEMBL614074 OR xref:chembl-CHEMBL1907609 OR xref:chembl-CHEMBL388 OR xref:chembl-CHEMBL2395 OR xref:chembl-CHEMBL2055 OR xref:chembl-CHEMBL2094 OR xref:chembl-CHEMBL2998 OR xref:chembl-CHEMBL270 OR xref:chembl-CHEMBL613835 OR xref:chembl-CHEMBL1907601 OR xref:chembl-CHEMBL2111455 OR xref:chembl-CHEMBL2111472 OR xref:chembl-CHEMBL2346486 OR xref:chembl-CHEMBL3784 OR xref:chembl-CHEMBL3563 OR xref:chembl-CHEMBL5136 OR xref:chembl-CHEMBL1945 OR xref:chembl-CHEMBL614721 OR xref:chembl-CHEMBL2095196 OR xref:chembl-CHEMBL2061 OR xref:chembl-CHEMBL3137261 OR xref:chembl-CHEMBL233 OR xref:chembl-CHEMBL614335 OR xref:chembl-CHEMBL6065 OR xref:chembl-CHEMBL359 OR xref:chembl-CHEMBL2094112 OR xref:chembl-CHEMBL613827 OR xref:chembl-CHEMBL247 OR xref:chembl-CHEMBL3611965 OR xref:chembl-CHEMBL614910 OR xref:chembl-CHEMBL3116 OR xref:chembl-CHEMBL3902 OR xref:chembl-CHEMBL267 OR xref:chembl-CHEMBL333 OR xref:chembl-CHEMBL5145 OR xref:chembl-CHEMBL2111349 OR xref:chembl-CHEMBL2111433 OR xref:chembl-CHEMBL2097173 OR xref:chembl-CHEMBL2111334 OR xref:chembl-CHEMBL2096990 OR xref:chembl-CHEMBL304 OR xref:chembl-CHEMBL613853 OR xref:chembl-CHEMBL614725 OR xref:chembl-CHEMBL614811 OR xref:chembl-CHEMBL4630734 OR xref:chembl-CHEMBL2916 OR xref:chembl-CHEMBL5724749 OR xref:chembl-CHEMBL3520 OR xref:chembl-CHEMBL613508 OR xref:chembl-CHEMBL614949) fields=
2026-02-05 19:18:21 | INFO     | silkroute.core.workflow.main | Pipeline: performing CrossRef enrichment with fields=['alphafold']
2026-02-05 19:18:21 | INFO     | silkroute.core.utils.crossref_enrichment | Running crossref enrichment for fields: ['alphafold']
Processed crossref fields: {'alphafold': [{'method': None, 'option': None}]}
Crossref fields: ['alphafold']
2026-02-05 19:18:21 | INFO     | silkroute.interfaces.crossref_enricher | Checking availability for interface: alphafold
2026-02-05 19:18:21 | INFO     | silkroute.interfaces.crossref_enricher | Checking required columns for alphafold:prediction...
2026-02-05 19:18:21 | INFO     | silkroute.interfaces.crossref_enricher | Building interface for alphafold...
2026-02-05 19:18:21 | INFO     | silkroute.interfaces.crossref_enricher | Prepared params for alphafold:prediction: {}
2026-02-05 19:18:24 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-O00591-F1-model_v6.pdb...
2026-02-05 19:18:26 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-O00748-F1-model_v6.pdb...
2026-02-05 19:18:26 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-O00748-5-F1-model_v6.pdb...
2026-02-05 19:18:26 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-O00748-4-F1-model_v6.pdb...
2026-02-05 19:18:27 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-O00748-2-F1-model_v6.pdb...
2026-02-05 19:18:29 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-O09028-F1-model_v6.pdb...
2026-02-05 19:18:31 | INFO     | silkroute.interfaces.alphafold | Structure AF-O15379-F1-model_v6.pdb already exists. Skipping download.
2026-02-05 19:18:31 | INFO     | silkroute.interfaces.alphafold | Structure AF-O15379-2-F1-model_v6.pdb already exists. Skipping download.
2026-02-05 19:18:33 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-O42275-F1-model_v6.pdb...
2026-02-05 19:18:35 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-O42713-F1-model_v6.pdb...
2026-02-05 19:18:36 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-O60341-F1-model_v6.pdb...
2026-02-05 19:18:37 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-O60341-2-F1-model_v6.pdb...
2026-02-05 19:18:38 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-O75530-F1-model_v6.pdb...
2026-02-05 19:18:39 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-O75530-3-F1-model_v6.pdb...
2026-02-05 19:18:39 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-O75530-2-F1-model_v6.pdb...
2026-02-05 19:18:41 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P00376-F1-model_v6.pdb...
2026-02-05 19:18:43 | INFO     | silkroute.interfaces.alphafold | Structure AF-P00533-F1-model_v6.pdb already exists. Skipping download.
2026-02-05 19:18:43 | INFO     | silkroute.interfaces.alphafold | Structure AF-P00533-4-F1-model_v6.pdb already exists. Skipping download.
2026-02-05 19:18:43 | INFO     | silkroute.interfaces.alphafold | Structure AF-P00533-3-F1-model_v6.pdb already exists. Skipping download.
2026-02-05 19:18:43 | INFO     | silkroute.interfaces.alphafold | Structure AF-P00533-2-F1-model_v6.pdb already exists. Skipping download.
2026-02-05 19:18:44 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P04629-F1-model_v6.pdb...
2026-02-05 19:18:45 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P04629-4-F1-model_v6.pdb...
2026-02-05 19:18:45 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P04629-3-F1-model_v6.pdb...
2026-02-05 19:18:46 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P04629-2-F1-model_v6.pdb...
2026-02-05 19:18:48 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P05177-F1-model_v6.pdb...
2026-02-05 19:18:50 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P05804-F1-model_v6.pdb...
2026-02-05 19:18:52 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P05979-F1-model_v6.pdb...
2026-02-05 19:18:54 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P06276-F1-model_v6.pdb...
2026-02-05 19:18:56 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P08238-F1-model_v6.pdb...
2026-02-05 19:18:58 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P08684-F1-model_v6.pdb...
2026-02-05 19:19:00 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P09467-F1-model_v6.pdb...
2026-02-05 19:19:01 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P10635-F1-model_v6.pdb...
2026-02-05 19:19:02 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P10635-2-F1-model_v6.pdb...
2026-02-05 19:19:04 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P14780-F1-model_v6.pdb...
2026-02-05 19:19:06 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P15309-F1-model_v6.pdb...
2026-02-05 19:19:06 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P15309-3-F1-model_v6.pdb...
2026-02-05 19:19:07 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P15309-2-F1-model_v6.pdb...
2026-02-05 19:19:09 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P15431-F1-model_v6.pdb...
2026-02-05 19:19:10 | INFO     | silkroute.interfaces.alphafold | Structure AF-P17174-F1-model_v6.pdb already exists. Skipping download.
2026-02-05 19:19:10 | INFO     | silkroute.interfaces.alphafold | Structure AF-P17174-2-F1-model_v6.pdb already exists. Skipping download.
2026-02-05 19:19:13 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P18031-F1-model_v6.pdb...
2026-02-05 19:19:15 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P18584-F1-model_v6.pdb...
2026-02-05 19:19:17 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P21397-F1-model_v6.pdb...
2026-02-05 19:19:17 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P21397-2-F1-model_v6.pdb...
2026-02-05 19:19:19 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P22303-F1-model_v6.pdb...
2026-02-05 19:19:19 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P22303-4-F1-model_v6.pdb...
2026-02-05 19:19:19 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P22303-3-F1-model_v6.pdb...
2026-02-05 19:19:20 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P22303-2-F1-model_v6.pdb...
2026-02-05 19:19:23 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P23739-F1-model_v6.pdb...
2026-02-05 19:19:24 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P24941-F1-model_v6.pdb...
2026-02-05 19:19:24 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P24941-2-F1-model_v6.pdb...
2026-02-05 19:19:27 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P27338-F1-model_v6.pdb...
2026-02-05 19:19:27 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P27338-2-F1-model_v6.pdb...
2026-02-05 19:19:29 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P28473-F1-model_v6.pdb...
2026-02-05 19:19:31 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P32300-F1-model_v6.pdb...
2026-02-05 19:19:33 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P33261-F1-model_v6.pdb...
2026-02-05 19:19:36 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P33527-F1-model_v6.pdb...
2026-02-05 19:19:36 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P33527-9-F1-model_v6.pdb...
2026-02-05 19:19:37 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P33527-8-F1-model_v6.pdb...
2026-02-05 19:19:37 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P33527-7-F1-model_v6.pdb...
2026-02-05 19:19:37 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P33527-6-F1-model_v6.pdb...
2026-02-05 19:19:38 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P33527-5-F1-model_v6.pdb...
2026-02-05 19:19:38 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P33527-4-F1-model_v6.pdb...
2026-02-05 19:19:38 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P33527-3-F1-model_v6.pdb...
2026-02-05 19:19:39 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P33527-2-F1-model_v6.pdb...
2026-02-05 19:19:41 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P38158-F1-model_v6.pdb...
2026-02-05 19:19:43 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P41144-F1-model_v6.pdb...
2026-02-05 19:19:45 | INFO     | silkroute.interfaces.alphafold | Structure AF-P42338-F1-model_v6.pdb already exists. Skipping download.
2026-02-05 19:19:47 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P53051-F1-model_v6.pdb...
2026-02-05 19:19:49 | INFO     | silkroute.interfaces.alphafold | Structure AF-P56524-F1-model_v6.pdb already exists. Skipping download.
2026-02-05 19:19:49 | INFO     | silkroute.interfaces.alphafold | Structure AF-P56524-2-F1-model_v6.pdb already exists. Skipping download.
2026-02-05 19:19:50 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P61169-F1-model_v6.pdb...
2026-02-05 19:19:51 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P61169-2-F1-model_v6.pdb...
2026-02-05 19:19:52 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P78334-F1-model_v6.pdb...
2026-02-05 19:19:53 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P78334-2-F1-model_v6.pdb...
2026-02-05 19:19:55 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P80457-F1-model_v6.pdb...
2026-02-05 19:19:57 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P81908-F1-model_v6.pdb...
2026-02-05 19:19:58 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P97266-F1-model_v6.pdb...
2026-02-05 19:20:00 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P97480-F1-model_v6.pdb...
2026-02-05 19:20:00 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P97480-2-F1-model_v6.pdb...
2026-02-05 19:20:02 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-P97612-F1-model_v6.pdb...
2026-02-05 19:20:04 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-Q01433-F1-model_v6.pdb...
2026-02-05 19:20:04 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-Q01433-5-F1-model_v6.pdb...
2026-02-05 19:20:05 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-Q01433-4-F1-model_v6.pdb...
2026-02-05 19:20:05 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-Q01433-3-F1-model_v6.pdb...
2026-02-05 19:20:05 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-Q01433-2-F1-model_v6.pdb...
2026-02-05 19:20:07 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-Q07343-F1-model_v6.pdb...
2026-02-05 19:20:08 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-Q07343-4-F1-model_v6.pdb...
2026-02-05 19:20:08 | INFO     | silkroute.interfaces.alphafold | Downloading structure AF-Q07343-3-F1-model_v6.pdb...

Using workflow will automatically handle the chaining of requests and data retrieval based on the defined parameters.

The return format are separated in 2 parts:
1. Data: The main data retrieved from the queries.
2. Metadata: Additional information about the retrieval process, such as query parameters, timestamps, and any errors encountered.

Data is distributed in a dictionary, where each key represents a different source of data, for example:
- 'uniprot' for protein sequences from UniProt
- 'chembl' for compound structures from ChEMBL
- 'uniprot_enrichment' for enriched protein data from UniProt

Uniprot_enrichment will only be present if enrichment is set to True.
If so, the dictionary will contain every enrichment used in 'uniprot_enrichment' key separated by '{source}_{endpoint}'.

In [3]:
data.keys()

dict_keys(['chembl', 'uniprot', 'uniprot_enrichment'])

In [6]:
data["uniprot_enrichment"].keys()

dict_keys(['brenda_getTemperatureOptimum', 'brenda_getTemperatureStability', 'brenda_getTemperatureRange'])

In [4]:
data["uniprot"].head(5)

,accession,protein_name,ec,organism_name,gene_primary,organism_id,lineage,sequence,length,alphafold_ids,...,sabiork_ids,string_ids,references,active_sites,temperature,ph,domains,variants,interactions,keyword
0,O00591,Gamma-aminobutyric acid receptor subunit pi,None,Homo sapiens,[GABRP],9606,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",MNYSLHLAFVCLSLFTERMCIQGSQFNVEVGRSDKLSLPGFENLTA...,440,[O00591],...,[],[9606.ENSP00000430100],[{'title': 'A novel class of GABAA receptor su...,[],[],[],[],"[{'type': 'Natural variant', 'id': 'VAR_020323...",[],"[3D-structure, Cell membrane, Chloride, Chlori..."
1,O00748,Cocaine esterase,[3.1.1.84],Homo sapiens,[CES2],9606,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",MRLHRLRARLSAVACGLLLLLVRGQGQDSASPIRTTHTGQVLGSLV...,559,[O00748],...,[O00748],[9606.ENSP00000499140],[{'title': 'Molecular cloning and characteriza...,"[{'type': 'Active site', 'description': 'Acyl-...",[],[],"[{'type': 'Motif', 'description': 'Prevents se...","[{'type': 'Natural variant', 'id': 'VAR_018396...","[{'accesion_a': 'O00748', 'geneName_a': '', 'a...","[Alternative initiation, Alternative splicing,..."
2,O09028,Gamma-aminobutyric acid receptor subunit pi,None,Rattus norvegicus,[Gabrp],10116,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",MSYSLYLAFVCLNLLAQRMCIQGNQFNVEVSRSDKLSLPGFENLTA...,440,[O09028],...,[],[10116.ENSRNOP00000048081],[{'title': 'A novel class of GABAA receptor su...,[],[],[],[],[],[],"[Cell membrane, Chloride, Chloride channel, Di..."
3,O15379,Histone deacetylase 3,[3.5.1.98],Homo sapiens,[HDAC3],9606,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",MAKTVAYFYDPDVGNFHYGAGHPMKPHRLALTHSLVLHYGLYKKMI...,428,[O15379],...,[O15379],[9606.ENSP00000302967],[{'title': 'Differential display cloning of a ...,"[{'type': 'Active site', 'description': '', 'l...",[],[],"[{'type': 'Region', 'description': 'Histone de...","[{'type': 'Natural variant', 'id': 'VAR_033988...","[{'accesion_a': 'O15379', 'geneName_a': '', 'a...","[3D-structure, Alternative splicing, Biologica..."
4,O42275,Acetylcholinesterase,[3.1.1.7],Electrophorus electricus,[ache],8005,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",MKILDALLFPVIFIMFFIHLSIAQTDPELTIMTRLGQVQGTRLPVP...,633,[O42275],...,[O42275],[8005.ENSEEEP00000024330],[{'title': 'Cloning and expression of acetylch...,"[{'type': 'Active site', 'description': 'Acyl-...",[],[],[],[],[],"[Cell membrane, Disulfide bond, Glycoprotein, ..."

### Search for proteins with a specific temperature stability and retrieve their sequences

In [5]:
data, meta = wf.run(
    mode="query_first", modality="protein", query="temperature:98", export_format="csv", enrich=True
)

2026-02-05 19:48:12 | INFO     | silkroute.core.workflow.main | Pipeline: fetching UniProt for query=cc_bpcp_temp_dependence:98 fields=
2026-02-05 19:48:14 | INFO     | silkroute.core.workflow.main | Pipeline: performing CrossRef enrichment with fields=['brenda_getTemperatureOptimum', 'brenda_getTemperatureStability', 'brenda_getTemperatureRange']
2026-02-05 19:48:14 | INFO     | silkroute.core.utils.crossref_enrichment | Running crossref enrichment for fields: ['brenda_getTemperatureOptimum', 'brenda_getTemperatureStability', 'brenda_getTemperatureRange']
Processed crossref fields: {'brenda': [{'method': 'getTemperatureOptimum', 'option': None}, {'method': 'getTemperatureStability', 'option': None}, {'method': 'getTemperatureRange', 'option': None}]}
Crossref fields: ['brenda_getTemperatureOptimum', 'brenda_getTemperatureStability', 'brenda_getTemperatureRange']
2026-02-05 19:48:14 | INFO     | silkroute.interfaces.crossref_enricher | Checking availability for interface: brenda
2026-02-05 19:48:14 | INFO     | silkroute.interfaces.crossref_enricher | Checking required columns for brenda:getTemperatureOptimum...
2026-02-05 19:48:14 | INFO     | silkroute.interfaces.crossref_enricher | Building interface for brenda...
2026-02-05 19:48:17 | INFO     | silkroute.interfaces.crossref_enricher | Prepared params for brenda:getTemperatureOptimum: {}
2026-02-05 19:49:01 | INFO     | silkroute.interfaces.crossref_enricher | Checking availability for interface: brenda
2026-02-05 19:49:01 | INFO     | silkroute.interfaces.crossref_enricher | Checking required columns for brenda:getTemperatureStability...
2026-02-05 19:49:01 | INFO     | silkroute.interfaces.crossref_enricher | Building interface for brenda...
2026-02-05 19:49:04 | INFO     | silkroute.interfaces.crossref_enricher | Prepared params for brenda:getTemperatureStability: {}
Error fetching data for getTemperatureStability with parameters {'ecNumber': '3.2.1.4'}: Server returned response (200) with invalid XML: Invalid XML content received (PCDATA invalid Char value 1, line 2, column 4147).

In [7]:
data["uniprot"].head(5)

,accession,protein_name,ec,organism_name,gene_primary,organism_id,lineage,sequence,length,alphafold_ids,...,sabiork_ids,string_ids,references,active_sites,temperature,ph,domains,variants,interactions,keyword
0,O08342,Endoglucanase A,[3.2.1.4],Paenibacillus barcinonensis,[celA],198119,"[Bacteria, Bacillati, Bacillota, Bacilli, Baci...",MTKTFKKFSIAGLALLFMATAAFAGWSTKASAADMRSLTAAQITAE...,400,[O08342],...,[],[],[{'title': 'Cloning of a new endoglucanase gen...,"[{'type': 'Active site', 'description': 'Proto...",[Optimum temperature is 40 degrees Celsius. Sh...,[Optimum pH is 4.0. Highly stable at acid pH. ...,[],[],[],"[Carbohydrate metabolism, Cellulose degradatio..."
1,P84142,Acylphosphatase,[3.6.1.7],Pyrococcus horikoshii (strain ATCC 700860 / DS...,[acyP],70601,"[Archaea, Methanobacteriati, Methanobacteriota...",MAIVRAHLKIYGRVQGVGFRWSMQREARKLGVNGWVRNLPDGSVEA...,91,[P84142],...,[P84142],[],[{'title': 'Complete sequence and gene organiz...,"[{'type': 'Active site', 'description': '', 'l...",[Optimum temperature is 98 degrees Celsius. Po...,[Optimum pH is 5.3 at 25 degrees Celsius.],"[{'type': 'Domain', 'description': 'Acylphosph...",[],[],"[3D-structure, Hydrolase, Reference proteome]"
2,P85124,Small basic protein 2,None,Anas platyrhynchos,None,8839,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",QVRKYCPKVGYCSSKCSKADVWSLSSDCKFYCCLPPGWK,39,[P85124],...,[],[],[{'title': 'Structural and physicochemical cha...,[],[Denaturation temperature (Td) is 98.3 degrees...,[],[],[],[],"[Direct protein sequencing, Disulfide bond, Py..."
3,Q58653,2-phospho-L-lactate transferase,[2.7.8.28],Methanocaldococcus jannaschii (strain ATCC 430...,[cofD],243232,"[Archaea, Methanobacteriati, Methanobacteriota...",MIFVITVLSGGTGTPKLLQGLKRVVNNEELAVIVNTGEDTWIGDLY...,311,[Q58653],...,[Q58653],[243232.MJ_1256],[{'title': 'Complete genome sequence of the me...,"[{'type': 'Binding site', 'description': '', '...",[Optimum temperature is about 37 degrees Celsi...,[],[],"[{'type': 'Mutagenesis', 'id': '', 'location':...",[],"[Magnesium, Reference proteome, Transferase]"
4,Q5S260,N-carbamoyl-D-amino acid hydrolase,[3.5.1.77],Ensifer adhaerens,None,106592,"[Bacteria, Pseudomonadati, Pseudomonadota, Alp...",MTRQMILAVGQQGPIARAETREQVVVRLLYMLTKAASRGANFIVFP...,304,[Q5S260],...,[],[],[{'title': 'Thermostable D-carbamoylase from S...,"[{'type': 'Active site', 'description': '', 'l...",[Optimum temperature is 60 degrees Celsius. Ve...,[Optimum pH is 7.0. Stable at pH 6.5-8.2.],"[{'type': 'Domain', 'description': 'CN hydrola...",[],[],"[Direct protein sequencing, Hydrolase]"

In [8]:
data["uniprot_enrichment"]["brenda_getTemperatureOptimum"]

,ec,organism,temperature_optimum,temperature_optimum_max
0,3.2.1.4,Aspergillus niger,-999,None
1,3.2.1.4,Rasamsonia emersonii,-999,None
2,3.2.1.4,Stegonsporium opalus,-999,None
3,3.2.1.4,Fibrobacter succinogenes,25,None
4,3.2.1.4,Marinobacter sp.,27,35
...,...,...,...,...
591,2.4.1.1,Sulfurisphaera tokodaii str. 7,75,None
592,2.4.1.1,Pyrococcus furiosus,80,None
593,2.4.1.1,Acetivibrio thermocellus,80,None
594,2.4.1.1,Thermus aquaticus,80,85
595,2.4.1.1,Aquifex aeolicus,100,None

### Search ppi interactions for proteins reported in Prostate cancer (DI-02663)

In [9]:
data, meta = wf.run(
    mode="query_first",
    modality="interaction",
    export_format="csv",
    query="(cc_disease:DI-02663)",
    interaction_type="protein-protein",
)

2026-02-05 20:21:13 | INFO     | silkroute.core.workflow.main | Pipeline: fetching UniProt for query=( cc_disease:DI-02663 ) fields=
2026-02-05 20:21:15 | INFO     | silkroute.core.workflow.main | Pipeline: fetching additional interaction sources for protein-protein interactions
2026-02-05 20:21:15 | INFO     | silkroute.interfaces.crossref_enricher | Checking availability for interface: biogrid
2026-02-05 20:21:15 | INFO     | silkroute.interfaces.crossref_enricher | Checking required columns for biogrid:interactions...
2026-02-05 20:21:15 | INFO     | silkroute.interfaces.crossref_enricher | Building interface for biogrid...
2026-02-05 20:21:15 | INFO     | silkroute.interfaces.crossref_enricher | Prepared params for biogrid:interactions: {}
2026-02-05 20:21:28 | INFO     | silkroute.interfaces.crossref_enricher | Checking availability for interface: string
2026-02-05 20:21:28 | INFO     | silkroute.interfaces.crossref_enricher | Checking required columns for string:interaction_partners...
2026-02-05 20:21:28 | INFO     | silkroute.interfaces.crossref_enricher | Building interface for string...
2026-02-05 20:21:28 | INFO     | silkroute.interfaces.crossref_enricher | Prepared params for string:interaction_partners: {}

In [10]:
data["uniprot"].head(5)

,accession,protein_name,ec,organism_name,gene_primary,organism_id,lineage,sequence,length,alphafold_ids,...,sabiork_ids,string_ids,references,active_sites,temperature,ph,domains,variants,interactions,keyword
0,O96017,Serine/threonine-protein kinase Chk2,[2.7.11.1],Homo sapiens,[CHEK2],9606,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",MSRESDVEAQQSHGSSACSQPHGSVTQSQGSSSQSQGISSSSTSTM...,543,[O96017],...,[],[9606.ENSP00000372023],[{'title': 'Linkage of ATM to cell cycle regul...,"[{'type': 'Active site', 'description': 'Proto...",[],[],"[{'type': 'Domain', 'description': 'FHA', 'loc...","[{'type': 'Natural variant', 'id': 'VAR_019101...","[{'accesion_a': 'O96017', 'geneName_a': '', 'a...","[3D-structure, Alternative splicing, Apoptosis..."
1,P21757,Macrophage scavenger receptor types I and II,None,Homo sapiens,[MSR1],9606,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",MEQWDHFHNQQEDTDSCSESVKFDARSMTALLPPNPKNSPSLQEKL...,451,[P21757],...,[],[9606.ENSP00000405453],[{'title': 'Human macrophage scavenger recepto...,[],[],[],"[{'type': 'Domain', 'description': 'Collagen-l...","[{'type': 'Natural variant', 'id': 'VAR_025190...","[{'accesion_a': 'P21757', 'geneName_a': '', 'a...","[3D-structure, Alternative splicing, Coiled co..."
2,P29323,Ephrin type-B receptor 2,[2.7.10.1],Homo sapiens,[EPHB2],9606,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",MALRRLGAALLLLPLLAAVEETLMDSTTATAELGWMVHPPSGWEEV...,1055,[P29323],...,[],[9606.ENSP00000383053],"[{'title': 'Overexpression of ERK, an EPH fami...","[{'type': 'Active site', 'description': 'Proto...",[],[],"[{'type': 'Domain', 'description': 'Eph LBD', ...","[{'type': 'Natural variant', 'id': 'VAR_032853...","[{'accesion_a': 'P29323', 'geneName_a': '', 'a...","[3D-structure, Alternative splicing, ATP-bindi..."
3,P50539,Max-interacting protein 1,None,Homo sapiens,[MXI1],9606,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",MERVKMINVQRLLEAAEFLERRERECEHGYASSFPSMPSPRLQHSK...,228,[P50539],...,[],[9606.ENSP00000331152],"[{'title': 'Mxi1, a protein that specifically ...",[],[],[],"[{'type': 'Domain', 'description': 'bHLH', 'lo...","[{'type': 'Natural variant', 'id': 'VAR_004499...","[{'accesion_a': 'P50539', 'geneName_a': '', 'a...","[Alternative splicing, Disease variant, DNA-bi..."
4,P60484,"Phosphatidylinositol 3,4,5-trisphosphate 3-pho...","[3.1.3.16, 3.1.3.48, 3.1.3.67]",Homo sapiens,[PTEN],9606,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",MTAIIKEIVSRNKRRYQEDGFDLDLTYIYPNIIAMGFPAERLEGVY...,403,[P60484],...,[],[9606.ENSP00000361021],"[{'title': 'TEP1, encoded by a candidate tumor...","[{'type': 'Active site', 'description': 'Phosp...",[],[],"[{'type': 'Domain', 'description': 'Phosphatas...","[{'type': 'Natural variant', 'id': 'VAR_026248...","[{'accesion_a': 'P60484', 'geneName_a': '', 'a...","[3D-structure, Acetylation, Alternative initia..."

In [12]:
data["uniprot_enrichment"]["biogrid_interactions"]

,interaction_b,synonyms_a,synonyms_b,organism_a,organism_b
0,CHEK2,COCA1|FCC1|HNPCC|HNPCC1|LCFS2,CDS1|CHK2|HuCds1|LFS2|PP1425|RAD53|hCds1,9606,9606
1,BRCA1,CDS1|CHK2|HuCds1|LFS2|PP1425|RAD53|hCds1,BRCAI|BRCC1|BROVCA1|FANCS|IRIS|PNCA4|PPP1R53|P...,9606,9606
2,BRCA1,CDS1|CHK2|HuCds1|LFS2|PP1425|RAD53|hCds1,BRCAI|BRCC1|BROVCA1|FANCS|IRIS|PNCA4|PPP1R53|P...,9606,9606
3,CHEK2,NFBD1,CDS1|CHK2|HuCds1|LFS2|PP1425|RAD53|hCds1,9606,9606
4,CHEK2,NFBD1,CDS1|CHK2|HuCds1|LFS2|PP1425|RAD53|hCds1,9606,9606
...,...,...,...,...,...
2072,STRAP,BCD1|CBA1|COPEB|CPBP|GBF|PAC1|ST12|ZF9,MAWD|PT-WD|UNRIP,9606,9606
2073,KLF6,CEB1|CEBP1,BCD1|CBA1|COPEB|CPBP|GBF|PAC1|ST12|ZF9,9606,9606
2074,ACTA2,BCD1|CBA1|COPEB|CPBP|GBF|PAC1|ST12|ZF9,AAT6|ACTSA|MYMY5,9606,9606
2075,TANGO6,BCD1|CBA1|COPEB|CPBP|GBF|PAC1|ST12|ZF9,TMCO7,9606,9606
2076,EPC1,BCD1|CBA1|COPEB|CPBP|GBF|PAC1|ST12|ZF9,Epl1,9606,9606

### Search pli interactions related to 'Human inmunodefificiency virus'

In [13]:
data, meta = wf.run(
    mode="query_first",
    modality="interaction",
    export_format="csv",
    query="Human immunodeficiency virus",
    interaction_type="protein-ligand",
)

2026-02-05 20:22:30 | INFO     | silkroute.core.workflow.main | Pipeline: fetching ChEMBL for query=Human immunodeficiency virus search_type=target
2026-02-05 20:22:30 | INFO     | silkroute.core.workflow.main | Pipeline: fetching UniProt for query=(xref:chembl-CHEMBL4523214 OR xref:chembl-CHEMBL613758 OR xref:chembl-CHEMBL378 OR xref:chembl-CHEMBL380 OR xref:chembl-CHEMBL612359 OR xref:chembl-CHEMBL613886 OR xref:chembl-CHEMBL2909 OR xref:chembl-CHEMBL3800 OR xref:chembl-CHEMBL243 OR xref:chembl-CHEMBL3471 OR xref:chembl-CHEMBL3852 OR xref:chembl-CHEMBL3463 OR xref:chembl-CHEMBL247 OR xref:chembl-CHEMBL3556 OR xref:chembl-CHEMBL5074 OR xref:chembl-CHEMBL613499 OR xref:chembl-CHEMBL613744 OR xref:chembl-CHEMBL613498 OR xref:chembl-CHEMBL613737 OR xref:chembl-CHEMBL4630879 OR xref:chembl-CHEMBL613551 OR xref:chembl-CHEMBL2362987 OR xref:chembl-CHEMBL3638323 OR xref:chembl-CHEMBL4296312 OR xref:chembl-CHEMBL4295909 OR xref:chembl-CHEMBL6066901 OR xref:chembl-CHEMBL248 OR xref:chembl-CHEMBL2632 OR xref:chembl-CHEMBL613127 OR xref:chembl-CHEMBL612319 OR xref:chembl-CHEMBL615047 OR xref:chembl-CHEMBL3831291 OR xref:chembl-CHEMBL6066444 OR xref:chembl-CHEMBL6066967 OR xref:chembl-CHEMBL1912 OR xref:chembl-CHEMBL612470 OR xref:chembl-CHEMBL370 OR xref:chembl-CHEMBL613124 OR xref:chembl-CHEMBL613126 OR xref:chembl-CHEMBL613132 OR xref:chembl-CHEMBL371 OR xref:chembl-CHEMBL377 OR xref:chembl-CHEMBL613496 OR xref:chembl-CHEMBL613715 OR xref:chembl-CHEMBL613717 OR xref:chembl-CHEMBL613760 OR xref:chembl-CHEMBL612680 OR xref:chembl-CHEMBL612237 OR xref:chembl-CHEMBL613837 OR xref:chembl-CHEMBL612776 OR xref:chembl-CHEMBL612780 OR xref:chembl-CHEMBL1293256 OR xref:chembl-CHEMBL4742266 OR xref:chembl-CHEMBL4802001 OR xref:chembl-CHEMBL5209660 OR xref:chembl-CHEMBL5209665 OR xref:chembl-CHEMBL6066913 OR xref:chembl-CHEMBL4977 OR xref:chembl-CHEMBL2857 OR xref:chembl-CHEMBL3982 OR xref:chembl-CHEMBL613120 OR xref:chembl-CHEMBL613131 OR xref:chembl-CHEMBL612672 OR xref:chembl-CHEMBL613493 OR xref:chembl-CHEMBL613494 OR xref:chembl-CHEMBL613558 OR xref:chembl-CHEMBL613725 OR xref:chembl-CHEMBL613735 OR xref:chembl-CHEMBL613742 OR xref:chembl-CHEMBL613754 OR xref:chembl-CHEMBL613757 OR xref:chembl-CHEMBL612395 OR xref:chembl-CHEMBL5369 OR xref:chembl-CHEMBL613332 OR xref:chembl-CHEMBL612760 OR xref:chembl-CHEMBL613205 OR xref:chembl-CHEMBL612946 OR xref:chembl-CHEMBL612983 OR xref:chembl-CHEMBL614756 OR xref:chembl-CHEMBL615051 OR xref:chembl-CHEMBL615055 OR xref:chembl-CHEMBL2189122 OR xref:chembl-CHEMBL2366720 OR xref:chembl-CHEMBL2367113 OR xref:chembl-CHEMBL2367227 OR xref:chembl-CHEMBL2396507 OR xref:chembl-CHEMBL3259470 OR xref:chembl-CHEMBL3259471 OR xref:chembl-CHEMBL3341579 OR xref:chembl-CHEMBL4295806 OR xref:chembl-CHEMBL4296394 OR xref:chembl-CHEMBL4296563 OR xref:chembl-CHEMBL4296609 OR xref:chembl-CHEMBL4296612 OR xref:chembl-CHEMBL4513196 OR xref:chembl-CHEMBL4523072 OR xref:chembl-CHEMBL4888473 OR xref:chembl-CHEMBL4888479 OR xref:chembl-CHEMBL5291624 OR xref:chembl-CHEMBL5291649) fields=

In [15]:
data["uniprot"].head(5)

,accession,protein_name,ec,organism_name,gene_primary,organism_id,lineage,sequence,length,alphafold_ids,...,sabiork_ids,string_ids,references,active_sites,temperature,ph,domains,variants,interactions,keyword
0,D4A7K7,G-protein coupled receptor 183,None,Rattus norvegicus,[Gpr183],10116,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",MANNFTTPLAASHGNNCDLYAHHSTARILMPLHYSLVFIIGLVGNL...,357,[D4A7K7],...,[],[10116.ENSRNOP00000035137],[{'title': 'Genome sequence of the Brown Norwa...,"[{'type': 'Binding site', 'description': '', '...",[],[],"[{'type': 'Region', 'description': 'Interactio...",[],[],"[Adaptive immunity, Cell membrane, Disulfide b..."
1,P01911,"HLA class II histocompatibility antigen, DRB1 ...",None,Homo sapiens,[HLA-DRB1],9606,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",MVCLKLPGGSCMTALTVTLMVLSSPLALSGDTRPRFLWQPKRECHF...,266,[P01911],...,[],[9606.ENSP00000353099],[{'title': 'Mutations and selection in the gen...,"[{'type': 'Binding site', 'description': '', '...",[],[],"[{'type': 'Domain', 'description': 'Ig-like C1...","[{'type': 'Natural variant', 'id': 'VAR_082703...","[{'accesion_a': 'P01911', 'geneName_a': '', 'a...","[3D-structure, Adaptive immunity, Cell membran..."
2,P04439,"HLA class I histocompatibility antigen, A alph...",None,Homo sapiens,[HLA-A],9606,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",MAVMAPRTLLLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,365,[P04439],...,[],[9606.ENSP00000379873],[{'title': 'The primary structure of HLA-A32 s...,"[{'type': 'Binding site', 'description': '', '...",[],[],"[{'type': 'Domain', 'description': 'Ig-like C1...","[{'type': 'Natural variant', 'id': 'VAR_082315...","[{'accesion_a': 'P04439', 'geneName_a': '', 'a...","[3D-structure, Adaptive immunity, Alternative ..."
3,P05412,Transcription factor Jun,None,Homo sapiens,[JUN],9606,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",MTAKMETTFYDDALNASFLPSESGPYGYSNPKILKQSMTLNLADPV...,331,[P05412],...,[],[9606.ENSP00000360266],[{'title': 'Structure and chromosomal localiza...,"[{'type': 'Site', 'description': 'Necessary fo...",[],[],"[{'type': 'Domain', 'description': 'bZIP', 'lo...","[{'type': 'Natural variant', 'id': 'VAR_012070...","[{'accesion_a': 'P05412', 'geneName_a': '', 'a...","[3D-structure, Acetylation, Activator, Direct ..."
4,P05627,Transcription factor Jun,None,Mus musculus,[Jun],10090,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",MTAKMETTFYDDALNASFLQSESGAYGYSNPKILKQSMTLNLADPV...,334,[P05627],...,[],[10090.ENSMUSP00000102711],[{'title': 'Transcriptional activation of c-ju...,"[{'type': 'Site', 'description': 'Necessary fo...",[],[],"[{'type': 'Domain', 'description': 'bZIP', 'lo...",[],"[{'accesion_a': 'P05627', 'geneName_a': '', 'a...","[Acetylation, Activator, DNA-binding, Isopepti..."

In [17]:
data["chembl"]

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,Transcription factor HIVEP2,36.0,False,CHEMBL4523214,"{'accession': 'P31629', 'component_description...",SINGLE PROTEIN,9606
1,[],Human immunodeficiency virus,Human immunodeficiency virus,31.0,False,CHEMBL613758,[],ORGANISM,12721
2,[],Human immunodeficiency virus 1,Human immunodeficiency virus 1,28.0,False,CHEMBL378,[],ORGANISM,11676
3,[],Human immunodeficiency virus 2,Human immunodeficiency virus 2,28.0,False,CHEMBL380,[],ORGANISM,11709
4,[],Human immunodeficiency virus 3,Human immunodeficiency virus 3,28.0,False,CHEMBL612359,[],ORGANISM,35274
...,...,...,...,...,...,...,...,...,...
95,[],Mammarenavirus juninense,Junin virus,9.0,False,CHEMBL4523072,[],ORGANISM,2169991
96,[],Powassan virus,Powassan virus,9.0,False,CHEMBL4888473,[],ORGANISM,11083
97,[],Una virus,Una virus,9.0,False,CHEMBL4888479,[],ORGANISM,59304
98,[],Oropouche virus,Oropouche virus,9.0,False,CHEMBL5291624,[],ORGANISM,118655
99,[],Heartland virus,Heartland virus,9.0,False,CHEMBL5291649,[],ORGANISM,1216928